### ISSUE TITLE
Panasonic DC-G9 high-res RAW: insufficient crop

### ISSUE THREAD

**Issue by hoedur** [darktable-org/rawspeed#170]
When opening a High Resolution RAW (the large variant with ~125 MB file size) with darktable 2.6.0, artifacts can be seen on the right border of the picture (panorama) or on the top border (portrait).

This issue was approved by @LebedevRI. More details are to follow if needed.

**Comment by hoedur** [comment]
Workaround: use the crop editing feature of the "raw black/white point" module:

1. Edit "~/.config/darktable/darktablerc"
2. Find the line "plugins/darkroom/rawprepare/allow_editing_crop=false"
3. Change "false" to "true"
4. Open darktable and go to the "RAW black/white point" module
5. There should be a slider "crop width"; increase this value until the artifacts are gone
6. If you don't see this slider, then you might first delete "~/.config/darktable/" (create a backup first, as this fries your settings!)

**Comment by kmilos** [comment]
Yep, both the single 20MP shot out of the hi-res sequence, _and_ the hi-res output as well seem to need extra 16px cropped.

The single shot has width of 5280 instead of the 5264 found in the normal mode.

More bizarrely, there is also this burst mode (sample also in RPU), where the width stayed the same as normal, but the height went up by 8 pixels (look like both top and bottom)!

**Comment by jsmucr** [comment]
Would it help if I provided raws in various different modes?

**Comment by kmilos** [comment]
> Would it help if I provided raws in various different modes?

They're all on RPU already AFAICT.

**Comment by kofa73** [comment]
Is this related to High-Res mode? My LX7, which has no such feature, is affected by a similar issue. @kmilos is aware of the bug report I've opened for darktable, but maybe it's worth linking here:
https://github.com/darktable-org/darktable/issues/14082

**Comment by jdneumeyer77** [comment]
This appears to be affecting the Panasonic S5 high-res raw files as well, but not the normal raw files. It was working fine, but I haven't kept up since my PR was merged for v7 Panasonic raw format a couple months ago. Now I'm getting pink garbage on the right side of hi-res as well. I haven't had time to investigate more, but it looks similar to https://github.com/darktable-org/darktable/issues/14082.

**Comment by jsmucr** [comment]
I think this approach with custom hardcoded crops is wrong in general. It's not just the hi-res mode. Bursts have different crop too. Also, the [0, 0, -58, 0] default crop is wrong because there are still some tiny artifacts visible.

It will never work well the way it is.

**Comment by jsmucr** [comment]
@kofa73 @jdneumeyer77 Yes, it's all the same thing. I'm working on a fix for the G9 static cases such as hi-res or burst modes, but that won't help with all the issues.

**Comment by jsmucr** [comment]
I've analyzed a collection of my G9 photos from May, and there's apparently no point in trying to fix it by adding more modes.
https://discuss.pixls.us/t/panasonic-g9-rawspeed-and-cropping/38236/5?u=newerth

The entire approach will need to change.
